# Generated by Django 4.2.25 on 2025-10-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
