# Generated by Django 4.2.25 on 2025-10-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ManyToManyField(through='order.OrderItem', to='menu.menu'),
        ),
    ]
